const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.ppstudio_lolapi,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Timer,
		C3.Plugins.Particles,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Sin,
		C3.Behaviors.Physics,
		C3.Behaviors.Rotate,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Behaviors.EightDir,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Platform,
		C3.Behaviors.wrap,
		C3.Behaviors.scrollto,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Exps.canvastolayerx,
		C3.Plugins.System.Exps.layertocanvasx,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Exps.layertocanvasy,
		C3.Plugins.System.Exps.canvastolayery,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.layoutscale,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SubInstanceVar,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.SetAcceleration,
		C3.Behaviors.MoveTo.Acts.SetDeceleration,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.TiledBg.Acts.AddInstanceVar,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Cnds.CompareHeight,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Exps.rgb,
		C3.Behaviors.scrollto.Cnds.IsEnabled,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Behaviors.EightDir.Exps.VectorX,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Cnds.OnTypewriterTextFinished,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Audio.Acts.SetPlaybackRate
	];
};
self.C3_JsPropNameTable = [
	{LoLAPI: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{Audio: 0},
	{AJAX: 0},
	{JSON: 0},
	{PlatformInfo: 0},
	{Fade: 0},
	{PilgrimsLogo: 0},
	{PlayButton: 0},
	{ContinueButton: 0},
	{Type: 0},
	{ButtonText: 0},
	{StageNumber: 0},
	{Poster1: 0},
	{Poster2: 0},
	{Poster3: 0},
	{Poster4: 0},
	{Poster5: 0},
	{Poster6: 0},
	{Poster7: 0},
	{Poster8: 0},
	{Poster9: 0},
	{Poster10: 0},
	{MapBKG: 0},
	{StageName: 0},
	{State: 0},
	{StagePoint: 0},
	{NextStage: 0},
	{MoveTo: 0},
	{Timer: 0},
	{Cell: 0},
	{Board: 0},
	{Chair: 0},
	{Table: 0},
	{BotleSmoke: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{MouseRunning: 0},
	{Bat: 0},
	{Sine: 0},
	{Neuron: 0},
	{Brain: 0},
	{CurrentAngle: 0},
	{Organs: 0},
	{Sequence: 0},
	{Original_Y: 0},
	{Node: 0},
	{Physics: 0},
	{Ball: 0},
	{X_InitialPos: 0},
	{Y_InitialPos: 0},
	{Rotate: 0},
	{ClockNail: 0},
	{NouronBackground: 0},
	{BasedelNodo: 0},
	{Leg2: 0},
	{LeftElbow: 0},
	{ID: 0},
	{NewAngle: 0},
	{LeftHarm: 0},
	{LeftKnee: 0},
	{LeftLeg: 0},
	{RightElbow: 0},
	{RightHarm: 0},
	{RightKnee: 0},
	{RightLeg: 0},
	{LeftElbow2: 0},
	{LeftHarm2: 0},
	{LeftKnee2: 0},
	{LeftLeg2: 0},
	{RightElbow2: 0},
	{RightHarm2: 0},
	{RightKnee2: 0},
	{RightLeg2: 0},
	{Boy: 0},
	{NotePlaceholder: 0},
	{InitialPosition: 0},
	{PlaceHolderID: 0},
	{Note: 0},
	{Confetti: 0},
	{Score: 0},
	{WinningBar: 0},
	{Note_GoalPoint: 0},
	{MuscleFlexedBalloon: 0},
	{Life: 0},
	{Stretcher: 0},
	{MusclesBackground: 0},
	{MusclesDungeon: 0},
	{MusclesBelt: 0},
	{Wires: 0},
	{Chain: 0},
	{BateryContainer: 0},
	{BatteryFence: 0},
	{HartBase: 0},
	{CurrentScale: 0},
	{Lungs: 0},
	{Aircontainer_Bar: 0},
	{MaxWidth: 0},
	{GrowthVel: 0},
	{GasesBar: 0},
	{Round: 0},
	{ButtonPushed_Y: 0},
	{OriginalY: 0},
	{IsPushed: 0},
	{Button: 0},
	{O2_LimitIndicator: 0},
	{CO2_LimitIndicator: 0},
	{TopBarPoint: 0},
	{MaxHeight: 0},
	{OxygenLevelBar: 0},
	{CO2_LevelBar: 0},
	{LungsBackground: 0},
	{DungeonWalls: 0},
	{OxigenMachine: 0},
	{WorkingTable: 0},
	{Lungs2: 0},
	{ButtonTable: 0},
	{ButtonBase: 0},
	{ButtonHighlight: 0},
	{OxigenBarContainer: 0},
	{CO2BarContainer: 0},
	{ButtonBase_TextBaloon: 0},
	{MyAngle: 0},
	{Is_InTheRoad: 0},
	{Ready: 0},
	{Orientation: 0},
	{IsGoingNormal: 0},
	{BLUE: 0},
	{RED: 0},
	{Pipe_Default: 0},
	{Pipe_Angle: 0},
	{Pipe_Crox: 0},
	{Blood: 0},
	{Hart: 0},
	{Leaver: 0},
	{HartContainer: 0},
	{HartTop: 0},
	{BloodBackground: 0},
	{StonesBackground: 0},
	{LeaverContainer: 0},
	{LeaverTop: 0},
	{TimeForNextParticle: 0},
	{SpeedRoad1: 0},
	{SpeedRoad2: 0},
	{ParticlesToWin: 0},
	{Stomach: 0},
	{MyRoad: 0},
	{CurrentCheckpoint: 0},
	{Food: 0},
	{Pin: 0},
	{TXT_Particles: 0},
	{Road: 0},
	{Number: 0},
	{StomachCheckPoint: 0},
	{StomachBG: 0},
	{StomachBottom: 0},
	{StomachContainer: 0},
	{StomachAcid: 0},
	{AcidSurface: 0},
	{AcidBubbles: 0},
	{SmashEffect: 0},
	{Maze: 0},
	{AbsortionPoints: 0},
	{"8Direction": 0},
	{Sine2: 0},
	{Poop: 0},
	{Solid: 0},
	{MazeWalls: 0},
	{CurrentHeight: 0},
	{PointsCount: 0},
	{TotalPoints: 0},
	{InitialHeight: 0},
	{WaterBar: 0},
	{Toilet: 0},
	{MazeBackground: 0},
	{WaterIndicatorContainer: 0},
	{Flash: 0},
	{IndicatorLight: 0},
	{Touched: 0},
	{AWSD: 0},
	{LongPipe_Maze: 0},
	{AnglePipe_Maze: 0},
	{WaterBubble: 0},
	{IntestineWall: 0},
	{InTheIntestine: 0},
	{Particle: 0},
	{BTN_Enzyme: 0},
	{TXT_EnzymeButtons: 0},
	{FlyingParticles: 0},
	{IntestineBackground: 0},
	{IntestineButtonsContainer: 0},
	{ButtonsBase: 0},
	{OpacityFactor: 0},
	{Stimulis: 0},
	{X_Initial: 0},
	{Y_Initial: 0},
	{Red: 0},
	{Green: 0},
	{Blue: 0},
	{Finger: 0},
	{Ears: 0},
	{StimuliAnimation: 0},
	{InTouch: 0},
	{FingerTouchingArea: 0},
	{EarsTouchingArea: 0},
	{EyesTouchingArea: 0},
	{PointNumber: 0},
	{Star: 0},
	{InitialWidth: 0},
	{GrowingVel: 0},
	{StimuliTimeBar: 0},
	{StimulisBackground: 0},
	{Dungeon: 0},
	{Lectern: 0},
	{CountDown: 0},
	{TV: 0},
	{TV_Interference: 0},
	{StimuliButtons: 0},
	{FingerLight: 0},
	{StarsPanel: 0},
	{TimerBarContainer: 0},
	{UngryEmogi: 0},
	{Ground: 0},
	{LeftFloor: 0},
	{Platform_floor: 0},
	{LeftGround: 0},
	{RightGround: 0},
	{Jumpthru: 0},
	{Platform1: 0},
	{SkinFloor: 0},
	{LeftPlatform: 0},
	{FloatingPlatform: 0},
	{DisapearingPlatform: 0},
	{Jacket: 0},
	{SunBlock: 0},
	{Water: 0},
	{Pool: 0},
	{CastleBackground: 0},
	{TreesBackground: 0},
	{Sun: 0},
	{JumoButton: 0},
	{BodyTemperatureBar: 0},
	{UVDAMAGEBar: 0},
	{CharacterHUD: 0},
	{TemperatureIndicator: 0},
	{UVIndicator: 0},
	{BottomTemBar: 0},
	{UVBar: 0},
	{ForwardSign: 0},
	{UpSign: 0},
	{Fence: 0},
	{Rock: 0},
	{Tree1: 0},
	{Arbust1: 0},
	{Arbust2: 0},
	{Arbust3: 0},
	{Connector1: 0},
	{Connector2: 0},
	{Connector3: 0},
	{BodyTemperature: 0},
	{UVDamage: 0},
	{ItsFreezzing: 0},
	{Genre: 0},
	{Platform: 0},
	{PlatformObject: 0},
	{Character: 0},
	{Splash: 0},
	{JumpSmoke: 0},
	{InitialY: 0},
	{InitialVel: 0},
	{ObstaclesVel: 0},
	{HasFinished: 0},
	{SpermCell: 0},
	{Wrap: 0},
	{SpermGroup: 0},
	{SpermTail_Secondary: 0},
	{SpermTail: 0},
	{BarContainer: 0},
	{Acid: 0},
	{Arrow: 0},
	{UterusWallsObstacle: 0},
	{Bubbles: 0},
	{OvumHUD: 0},
	{SpermCellHUD: 0},
	{Ovum: 0},
	{SpermBackground: 0},
	{UterusWall: 0},
	{UterusWall2: 0},
	{SpermGear: 0},
	{SpermBar: 0},
	{ArrowContainer: 0},
	{InitialZoom: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{X_FinalPos: 0},
	{Y_FinalPos: 0},
	{Patino: 0},
	{PatinoHead: 0},
	{PatinoFace: 0},
	{Mouth: 0},
	{DialogBox: 0},
	{TXT_Dialogs: 0},
	{ButtonForward: 0},
	{Hand: 0},
	{Clouds: 0},
	{Moon: 0},
	{CastleMenu: 0},
	{Mountain2: 0},
	{Mountain1: 0},
	{Hill2: 0},
	{Hill1: 0},
	{Hill3: 0},
	{GraveMenu: 0},
	{Gamelogo: 0},
	{Ray: 0},
	{TB_FlashEffect: 0},
	{RainDrop: 0},
	{Wires1: 0},
	{Wires2: 0},
	{Wires3: 0},
	{Ray_Sparks: 0},
	{BtnNewGame: 0},
	{BtnContinue: 0},
	{AnalogStick_Base: 0},
	{Stick: 0},
	{TestingText: 0},
	{ScreenTransition: 0},
	{MousePointer: 0},
	{Dialog_Elements: 0},
	{ArmsAndLegs: 0},
	{Pipes: 0},
	{TouchingAreaObjects: 0},
	{SkinElements: 0},
	{Muscles: 0},
	{Posters: 0},
	{Lungs_Both: 0},
	{RandomRainLayer: 0},
	{Lang: 0},
	{CurrentStage: 0},
	{MinigameState: 0},
	{CurrentText: 0},
	{ShowIntro: 0},
	{NextLayoutName: 0},
	{NextLayoutName_Parameter: 0},
	{RandomSide: 0},
	{MapState: 0},
	{CurrentNode: 0},
	{SequenceLong: 0},
	{SequenceNumber: 0},
	{Parameter0: 0},
	{TimeToNextNode: 0},
	{CurrentNoteVelocity: 0},
	{RandomPosition: 0},
	{X_Pos: 0},
	{Y_Pos: 0},
	{Random_P: 0},
	{IndicatorsWidth: 0},
	{RandomParticle: 0},
	{RandomRoad: 0},
	{RandomSmash: 0},
	{PipesCount: 0},
	{randomTime: 0},
	{ParticleCounter: 0},
	{IntestineScore: 0},
	{RandomAnimation: 0},
	{PreviousStimuli: 0},
	{NewStimuli: 0},
	{RandomObstacle: 0},
	{RandomDirection: 0},
	{DialogBox_SpacingTOP_BOTTOM: 0},
	{TimeToStartTalking: 0},
	{TypeWritingTime: 0},
	{DialogBox_SpacingRight: 0},
	{CurrentVoice: 0},
	{NewVoice: 0},
	{RandomFaceAnimation: 0},
	{RandomLooseAnimation: 0}
];

self.InstanceType = {
	LoLAPI: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	PlatformInfo: class extends self.IInstance {},
	PilgrimsLogo: class extends self.ISpriteInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	ContinueButton: class extends self.ISpriteInstance {},
	ButtonText: class extends self.ITextInstance {},
	Poster1: class extends self.ISpriteInstance {},
	Poster2: class extends self.ISpriteInstance {},
	Poster3: class extends self.ISpriteInstance {},
	Poster4: class extends self.ISpriteInstance {},
	Poster5: class extends self.ISpriteInstance {},
	Poster6: class extends self.ISpriteInstance {},
	Poster7: class extends self.ISpriteInstance {},
	Poster8: class extends self.ISpriteInstance {},
	Poster9: class extends self.ISpriteInstance {},
	Poster10: class extends self.ISpriteInstance {},
	MapBKG: class extends self.ISpriteInstance {},
	StagePoint: class extends self.ISpriteInstance {},
	Cell: class extends self.ISpriteInstance {},
	Board: class extends self.ISpriteInstance {},
	Chair: class extends self.ISpriteInstance {},
	Table: class extends self.ISpriteInstance {},
	BotleSmoke: class extends self.IParticlesInstance {},
	MouseRunning: class extends self.ISpriteInstance {},
	Bat: class extends self.ISpriteInstance {},
	Neuron: class extends self.ISpriteInstance {},
	Brain: class extends self.ISpriteInstance {},
	Organs: class extends self.ISpriteInstance {},
	Node: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	Timer: class extends self.ISpriteInstance {},
	ClockNail: class extends self.ISpriteInstance {},
	NouronBackground: class extends self.ITiledBackgroundInstance {},
	BasedelNodo: class extends self.ISpriteInstance {},
	Leg2: class extends self.ISpriteInstance {},
	LeftElbow: class extends self.ISpriteInstance {},
	LeftHarm: class extends self.ISpriteInstance {},
	LeftKnee: class extends self.ISpriteInstance {},
	LeftLeg: class extends self.ISpriteInstance {},
	RightElbow: class extends self.ISpriteInstance {},
	RightHarm: class extends self.ISpriteInstance {},
	RightKnee: class extends self.ISpriteInstance {},
	RightLeg: class extends self.ISpriteInstance {},
	LeftElbow2: class extends self.ISpriteInstance {},
	LeftHarm2: class extends self.ISpriteInstance {},
	LeftKnee2: class extends self.ISpriteInstance {},
	LeftLeg2: class extends self.ISpriteInstance {},
	RightElbow2: class extends self.ISpriteInstance {},
	RightHarm2: class extends self.ISpriteInstance {},
	RightKnee2: class extends self.ISpriteInstance {},
	RightLeg2: class extends self.ISpriteInstance {},
	Boy: class extends self.ISpriteInstance {},
	NotePlaceholder: class extends self.ISpriteInstance {},
	Note: class extends self.ISpriteInstance {},
	Confetti: class extends self.IParticlesInstance {},
	WinningBar: class extends self.ITiledBackgroundInstance {},
	Note_GoalPoint: class extends self.ISpriteInstance {},
	MuscleFlexedBalloon: class extends self.ISpriteInstance {},
	Life: class extends self.ISpriteInstance {},
	Stretcher: class extends self.ISpriteInstance {},
	MusclesBackground: class extends self.ISpriteInstance {},
	MusclesDungeon: class extends self.ISpriteInstance {},
	MusclesBelt: class extends self.ISpriteInstance {},
	Wires: class extends self.ISpriteInstance {},
	Chain: class extends self.ISpriteInstance {},
	BateryContainer: class extends self.ISpriteInstance {},
	BatteryFence: class extends self.ISpriteInstance {},
	HartBase: class extends self.ISpriteInstance {},
	Lungs: class extends self.ISpriteInstance {},
	Aircontainer_Bar: class extends self.ISpriteInstance {},
	GasesBar: class extends self.ITiledBackgroundInstance {},
	Button: class extends self.ISpriteInstance {},
	O2_LimitIndicator: class extends self.ITiledBackgroundInstance {},
	CO2_LimitIndicator: class extends self.ITiledBackgroundInstance {},
	TopBarPoint: class extends self.ISpriteInstance {},
	OxygenLevelBar: class extends self.ITiledBackgroundInstance {},
	CO2_LevelBar: class extends self.ITiledBackgroundInstance {},
	LungsBackground: class extends self.ISpriteInstance {},
	DungeonWalls: class extends self.ISpriteInstance {},
	OxigenMachine: class extends self.ISpriteInstance {},
	WorkingTable: class extends self.ISpriteInstance {},
	Lungs2: class extends self.ISpriteInstance {},
	ButtonTable: class extends self.ISpriteInstance {},
	ButtonBase: class extends self.ISpriteInstance {},
	ButtonHighlight: class extends self.ISpriteInstance {},
	OxigenBarContainer: class extends self.ISpriteInstance {},
	CO2BarContainer: class extends self.ISpriteInstance {},
	ButtonBase_TextBaloon: class extends self.ISpriteInstance {},
	Pipe_Default: class extends self.ISpriteInstance {},
	Pipe_Angle: class extends self.ISpriteInstance {},
	Pipe_Crox: class extends self.ISpriteInstance {},
	Blood: class extends self.ITiledBackgroundInstance {},
	Hart: class extends self.ISpriteInstance {},
	Leaver: class extends self.ISpriteInstance {},
	HartContainer: class extends self.ISpriteInstance {},
	HartTop: class extends self.ISpriteInstance {},
	BloodBackground: class extends self.ISpriteInstance {},
	StonesBackground: class extends self.ISpriteInstance {},
	LeaverContainer: class extends self.ISpriteInstance {},
	LeaverTop: class extends self.ISpriteInstance {},
	Stomach: class extends self.ISpriteInstance {},
	Food: class extends self.ISpriteInstance {},
	TXT_Particles: class extends self.ITextInstance {},
	StomachCheckPoint: class extends self.ISpriteInstance {},
	StomachBG: class extends self.ISpriteInstance {},
	StomachBottom: class extends self.ISpriteInstance {},
	StomachContainer: class extends self.ISpriteInstance {},
	StomachAcid: class extends self.ISpriteInstance {},
	AcidSurface: class extends self.ISpriteInstance {},
	AcidBubbles: class extends self.ISpriteInstance {},
	SmashEffect: class extends self.ISpriteInstance {},
	Maze: class extends self.ISpriteInstance {},
	AbsortionPoints: class extends self.ISpriteInstance {},
	Poop: class extends self.ISpriteInstance {},
	MazeWalls: class extends self.ITiledBackgroundInstance {},
	WaterBar: class extends self.ITiledBackgroundInstance {},
	Toilet: class extends self.ISpriteInstance {},
	MazeBackground: class extends self.ISpriteInstance {},
	WaterIndicatorContainer: class extends self.ISpriteInstance {},
	IndicatorLight: class extends self.ISpriteInstance {},
	AWSD: class extends self.ISpriteInstance {},
	LongPipe_Maze: class extends self.ITiledBackgroundInstance {},
	AnglePipe_Maze: class extends self.ISpriteInstance {},
	WaterBubble: class extends self.ISpriteInstance {},
	IntestineWall: class extends self.ITiledBackgroundInstance {},
	Particle: class extends self.ISpriteInstance {},
	BTN_Enzyme: class extends self.ISpriteInstance {},
	TXT_EnzymeButtons: class extends self.ITextInstance {},
	FlyingParticles: class extends self.ISpriteInstance {},
	IntestineBackground: class extends self.ISpriteInstance {},
	IntestineButtonsContainer: class extends self.ISpriteInstance {},
	ButtonsBase: class extends self.ISpriteInstance {},
	Stimulis: class extends self.ISpriteInstance {},
	Finger: class extends self.ISpriteInstance {},
	Ears: class extends self.ISpriteInstance {},
	FingerTouchingArea: class extends self.ISpriteInstance {},
	EarsTouchingArea: class extends self.ISpriteInstance {},
	EyesTouchingArea: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	StimuliTimeBar: class extends self.ITiledBackgroundInstance {},
	StimulisBackground: class extends self.ISpriteInstance {},
	Dungeon: class extends self.ISpriteInstance {},
	Lectern: class extends self.ISpriteInstance {},
	CountDown: class extends self.ISpriteInstance {},
	TV: class extends self.ISpriteInstance {},
	TV_Interference: class extends self.ISpriteInstance {},
	StimuliButtons: class extends self.ISpriteInstance {},
	FingerLight: class extends self.ISpriteInstance {},
	StarsPanel: class extends self.ISpriteInstance {},
	TimerBarContainer: class extends self.ISpriteInstance {},
	UngryEmogi: class extends self.ISpriteInstance {},
	Ground: class extends self.ITiledBackgroundInstance {},
	LeftFloor: class extends self.ISpriteInstance {},
	Platform_floor: class extends self.ITiledBackgroundInstance {},
	LeftGround: class extends self.ITiledBackgroundInstance {},
	RightGround: class extends self.ITiledBackgroundInstance {},
	Platform1: class extends self.ISpriteInstance {},
	SkinFloor: class extends self.ISpriteInstance {},
	LeftPlatform: class extends self.ISpriteInstance {},
	FloatingPlatform: class extends self.ITiledBackgroundInstance {},
	DisapearingPlatform: class extends self.ISpriteInstance {},
	Jacket: class extends self.ISpriteInstance {},
	SunBlock: class extends self.ISpriteInstance {},
	Water: class extends self.ISpriteInstance {},
	Pool: class extends self.ISpriteInstance {},
	CastleBackground: class extends self.ISpriteInstance {},
	TreesBackground: class extends self.ISpriteInstance {},
	Sun: class extends self.ISpriteInstance {},
	JumoButton: class extends self.ISpriteInstance {},
	BodyTemperatureBar: class extends self.ITiledBackgroundInstance {},
	UVDAMAGEBar: class extends self.ITiledBackgroundInstance {},
	CharacterHUD: class extends self.ISpriteInstance {},
	TemperatureIndicator: class extends self.ISpriteInstance {},
	UVIndicator: class extends self.ISpriteInstance {},
	BottomTemBar: class extends self.ISpriteInstance {},
	UVBar: class extends self.ISpriteInstance {},
	ForwardSign: class extends self.ISpriteInstance {},
	UpSign: class extends self.ISpriteInstance {},
	Fence: class extends self.ITiledBackgroundInstance {},
	Rock: class extends self.ISpriteInstance {},
	Tree1: class extends self.ISpriteInstance {},
	Arbust1: class extends self.ISpriteInstance {},
	Arbust2: class extends self.ISpriteInstance {},
	Arbust3: class extends self.ISpriteInstance {},
	Connector1: class extends self.ITiledBackgroundInstance {},
	Connector2: class extends self.ITiledBackgroundInstance {},
	Connector3: class extends self.ITiledBackgroundInstance {},
	PlatformObject: class extends self.ISpriteInstance {},
	Character: class extends self.ISpriteInstance {},
	Splash: class extends self.ISpriteInstance {},
	JumpSmoke: class extends self.ISpriteInstance {},
	SpermCell: class extends self.ISpriteInstance {},
	SpermGroup: class extends self.ISpriteInstance {},
	SpermTail_Secondary: class extends self.ISpriteInstance {},
	SpermTail: class extends self.ISpriteInstance {},
	BarContainer: class extends self.ISpriteInstance {},
	Acid: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	UterusWallsObstacle: class extends self.ISpriteInstance {},
	Bubbles: class extends self.ISpriteInstance {},
	OvumHUD: class extends self.ISpriteInstance {},
	SpermCellHUD: class extends self.ISpriteInstance {},
	Ovum: class extends self.ISpriteInstance {},
	SpermBackground: class extends self.ITiledBackgroundInstance {},
	UterusWall: class extends self.ITiledBackgroundInstance {},
	UterusWall2: class extends self.ITiledBackgroundInstance {},
	SpermGear: class extends self.ISpriteInstance {},
	SpermBar: class extends self.ITiledBackgroundInstance {},
	ArrowContainer: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	Patino: class extends self.ISpriteInstance {},
	PatinoHead: class extends self.ISpriteInstance {},
	PatinoFace: class extends self.ISpriteInstance {},
	Mouth: class extends self.ISpriteInstance {},
	DialogBox: class extends self.ISpriteInstance {},
	TXT_Dialogs: class extends self.ITextInstance {},
	ButtonForward: class extends self.ISpriteInstance {},
	Hand: class extends self.ISpriteInstance {},
	Clouds: class extends self.ISpriteInstance {},
	Moon: class extends self.ISpriteInstance {},
	CastleMenu: class extends self.ISpriteInstance {},
	Mountain2: class extends self.ISpriteInstance {},
	Mountain1: class extends self.ISpriteInstance {},
	Hill2: class extends self.ISpriteInstance {},
	Hill1: class extends self.ISpriteInstance {},
	Hill3: class extends self.ISpriteInstance {},
	GraveMenu: class extends self.ISpriteInstance {},
	Gamelogo: class extends self.ISpriteInstance {},
	Ray: class extends self.ISpriteInstance {},
	TB_FlashEffect: class extends self.ITiledBackgroundInstance {},
	RainDrop: class extends self.ISpriteInstance {},
	Wires1: class extends self.ISpriteInstance {},
	Wires2: class extends self.ISpriteInstance {},
	Wires3: class extends self.ISpriteInstance {},
	Ray_Sparks: class extends self.IParticlesInstance {},
	BtnNewGame: class extends self.ISpriteInstance {},
	BtnContinue: class extends self.ISpriteInstance {},
	AnalogStick_Base: class extends self.ISpriteInstance {},
	Stick: class extends self.ISpriteInstance {},
	TestingText: class extends self.ITextInstance {},
	ScreenTransition: class extends self.ISpriteInstance {},
	MousePointer: class extends self.ISpriteInstance {},
	Dialog_Elements: class extends self.ISpriteInstance {},
	ArmsAndLegs: class extends self.ISpriteInstance {},
	Pipes: class extends self.ISpriteInstance {},
	TouchingAreaObjects: class extends self.ISpriteInstance {},
	SkinElements: class extends self.ISpriteInstance {},
	Muscles: class extends self.ISpriteInstance {},
	Posters: class extends self.ISpriteInstance {},
	Lungs_Both: class extends self.ISpriteInstance {}
}