const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.ppstudio_lolapi,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Timer,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Behaviors.EightDir,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Platform,
		C3.Behaviors.jumpthru,
		C3.Behaviors.wrap,
		C3.Behaviors.scrollto,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.TiledBg.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.SetAcceleration,
		C3.Behaviors.MoveTo.Acts.SetDeceleration,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.TiledBg.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Exps.layoutscale,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Cnds.CompareHeight,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Exps.viewporttop,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Behaviors.scrollto.Cnds.IsEnabled,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Behaviors.EightDir.Exps.VectorX,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles
	];
};
self.C3_JsPropNameTable = [
	{LoLAPI: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{Audio: 0},
	{AJAX: 0},
	{JSON: 0},
	{PlatformInfo: 0},
	{Fade: 0},
	{PilgrimsLogo: 0},
	{PlayButton: 0},
	{ContinueButton: 0},
	{Type: 0},
	{ButtonText: 0},
	{MapBKG: 0},
	{StageNumber: 0},
	{StageName: 0},
	{State: 0},
	{StagePoint: 0},
	{NextStage: 0},
	{MoveTo: 0},
	{Timer: 0},
	{Cell: 0},
	{Neuron: 0},
	{Brain: 0},
	{Organs: 0},
	{Sequence: 0},
	{Node: 0},
	{Ball: 0},
	{X_InitialPos: 0},
	{Y_InitialPos: 0},
	{Rotate: 0},
	{ClockNail: 0},
	{Boy: 0},
	{ID: 0},
	{NewAngle: 0},
	{LeftHarm: 0},
	{RightHarm: 0},
	{RightLeg: 0},
	{LeftLeg: 0},
	{NotePlaceholder: 0},
	{InitialPosition: 0},
	{PlaceHolderID: 0},
	{Note: 0},
	{Confetti: 0},
	{Score: 0},
	{WinningBar: 0},
	{Note_GoalPoint: 0},
	{MuscleFlexedBalloon: 0},
	{Life: 0},
	{CurrentScale: 0},
	{Lungs: 0},
	{Aircontainer_Bar: 0},
	{MaxWidth: 0},
	{GrowthVel: 0},
	{GasesBar: 0},
	{Round: 0},
	{Sine: 0},
	{Button: 0},
	{O2_Icon: 0},
	{CO2_Icon: 0},
	{O2_LimitIndicator: 0},
	{CO2_LimitIndicator: 0},
	{TopBarPoint: 0},
	{MaxHeight: 0},
	{OxygenLevelBar: 0},
	{CO2_LevelBar: 0},
	{MyAngle: 0},
	{Is_InTheRoad: 0},
	{Ready: 0},
	{Orientation: 0},
	{Pipe_Default: 0},
	{Pipe_Angle: 0},
	{Pipe_Crox: 0},
	{Pipe_IoOut: 0},
	{Blood: 0},
	{Hart: 0},
	{Leaver: 0},
	{TimeForNextParticle: 0},
	{SpeedRoad1: 0},
	{SpeedRoad2: 0},
	{ParticlesToWin: 0},
	{Stomach: 0},
	{StomachTop: 0},
	{MyRoad: 0},
	{CurrentCheckpoint: 0},
	{Food: 0},
	{Pin: 0},
	{TXT_Particles: 0},
	{Road: 0},
	{Number: 0},
	{StomachCheckPoint: 0},
	{Maze: 0},
	{AbsortionPoints: 0},
	{"8Direction": 0},
	{Poop: 0},
	{Solid: 0},
	{MazeWalls: 0},
	{CurrentHeight: 0},
	{PointsCount: 0},
	{TotalPoints: 0},
	{InitialHeight: 0},
	{WaterBar: 0},
	{DropIcon: 0},
	{Toilet: 0},
	{Cruceta: 0},
	{Direction: 0},
	{CrucetaButton: 0},
	{IntestineWall: 0},
	{InTheIntestine: 0},
	{Particle: 0},
	{BTN_Enzyme: 0},
	{TXT_EnzymeButtons: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{FlyingParticles: 0},
	{OpacityFactor: 0},
	{Stimulis: 0},
	{X_Initial: 0},
	{Y_Initial: 0},
	{HandOut: 0},
	{Ears: 0},
	{StimuliAnimation: 0},
	{InTouch: 0},
	{HandTouchingArea: 0},
	{EarsTouchingArea: 0},
	{EyesTouchingArea: 0},
	{PointNumber: 0},
	{Star: 0},
	{InitialWidth: 0},
	{StimuliTimeBar: 0},
	{BodyTemperature: 0},
	{UVDamage: 0},
	{ItsFreezzing: 0},
	{Genre: 0},
	{Platform: 0},
	{Character: 0},
	{Jumpthru: 0},
	{SkinFloor: 0},
	{SunBlock: 0},
	{Jacket: 0},
	{MovingPlatform: 0},
	{Sun: 0},
	{Pool: 0},
	{DisapearingPlatform: 0},
	{BodyTemperatureBar: 0},
	{UVDAMAGEBar: 0},
	{JumoButton: 0},
	{CharacterPopUp: 0},
	{InitialY: 0},
	{InitialVel: 0},
	{ObstaclesVel: 0},
	{HasFinished: 0},
	{SpermCell: 0},
	{Wrap: 0},
	{SpermGroup: 0},
	{UterusWalls: 0},
	{Sine2: 0},
	{Acid: 0},
	{Arrow: 0},
	{UterusWallsObstacle: 0},
	{Bubbles: 0},
	{OvumHUD: 0},
	{SpermCellHUD: 0},
	{Ovum: 0},
	{InitialZoom: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{X_FinalPos: 0},
	{Y_FinalPos: 0},
	{CellAvatar: 0},
	{DialogBox: 0},
	{TXT_Dialogs: 0},
	{ButtonForward: 0},
	{Hand: 0},
	{Dialog_Elements: 0},
	{ArmsAndLegs: 0},
	{Pipes: 0},
	{TouchingAreaObjects: 0},
	{SkinElements: 0},
	{Lang: 0},
	{CurrentStage: 0},
	{MinigameState: 0},
	{CurrentText: 0},
	{ShowIntro: 0},
	{MapState: 0},
	{CurrentNode: 0},
	{SequenceLong: 0},
	{SequenceNumber: 0},
	{Parameter0: 0},
	{TimeToNextNode: 0},
	{CurrentNoteVelocity: 0},
	{RandomPosition: 0},
	{X_Pos: 0},
	{Y_Pos: 0},
	{Random_P: 0},
	{IndicatorsWidth: 0},
	{RandomParticle: 0},
	{RandomRoad: 0},
	{PipesCount: 0},
	{randomTime: 0},
	{ParticleCounter: 0},
	{IntestineScore: 0},
	{RandomAnimation: 0},
	{PickedCharacter: 0},
	{RandomObstacle: 0},
	{RandomDirection: 0},
	{DialogBox_SpacingTOP_BOTTOM: 0},
	{DialogBox_SpacingRight: 0}
];

self.InstanceType = {
	LoLAPI: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	PlatformInfo: class extends self.IInstance {},
	PilgrimsLogo: class extends self.ISpriteInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	ContinueButton: class extends self.ISpriteInstance {},
	ButtonText: class extends self.ITextInstance {},
	MapBKG: class extends self.ISpriteInstance {},
	StagePoint: class extends self.ISpriteInstance {},
	Cell: class extends self.ISpriteInstance {},
	Neuron: class extends self.ISpriteInstance {},
	Brain: class extends self.ISpriteInstance {},
	Organs: class extends self.ISpriteInstance {},
	Node: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	Timer: class extends self.ISpriteInstance {},
	ClockNail: class extends self.ISpriteInstance {},
	Boy: class extends self.ISpriteInstance {},
	LeftHarm: class extends self.ISpriteInstance {},
	RightHarm: class extends self.ISpriteInstance {},
	RightLeg: class extends self.ISpriteInstance {},
	LeftLeg: class extends self.ISpriteInstance {},
	NotePlaceholder: class extends self.ISpriteInstance {},
	Note: class extends self.ISpriteInstance {},
	Confetti: class extends self.IParticlesInstance {},
	WinningBar: class extends self.ITiledBackgroundInstance {},
	Note_GoalPoint: class extends self.ISpriteInstance {},
	MuscleFlexedBalloon: class extends self.ISpriteInstance {},
	Life: class extends self.ISpriteInstance {},
	Lungs: class extends self.ISpriteInstance {},
	Aircontainer_Bar: class extends self.ISpriteInstance {},
	GasesBar: class extends self.ITiledBackgroundInstance {},
	Button: class extends self.ISpriteInstance {},
	O2_Icon: class extends self.ISpriteInstance {},
	CO2_Icon: class extends self.ISpriteInstance {},
	O2_LimitIndicator: class extends self.ITiledBackgroundInstance {},
	CO2_LimitIndicator: class extends self.ITiledBackgroundInstance {},
	TopBarPoint: class extends self.ISpriteInstance {},
	OxygenLevelBar: class extends self.ITiledBackgroundInstance {},
	CO2_LevelBar: class extends self.ITiledBackgroundInstance {},
	Pipe_Default: class extends self.ISpriteInstance {},
	Pipe_Angle: class extends self.ISpriteInstance {},
	Pipe_Crox: class extends self.ISpriteInstance {},
	Pipe_IoOut: class extends self.ISpriteInstance {},
	Blood: class extends self.ITiledBackgroundInstance {},
	Hart: class extends self.ISpriteInstance {},
	Leaver: class extends self.ISpriteInstance {},
	Stomach: class extends self.ISpriteInstance {},
	StomachTop: class extends self.ISpriteInstance {},
	Food: class extends self.ISpriteInstance {},
	TXT_Particles: class extends self.ITextInstance {},
	StomachCheckPoint: class extends self.ISpriteInstance {},
	Maze: class extends self.ISpriteInstance {},
	AbsortionPoints: class extends self.ISpriteInstance {},
	Poop: class extends self.ISpriteInstance {},
	MazeWalls: class extends self.ITiledBackgroundInstance {},
	WaterBar: class extends self.ITiledBackgroundInstance {},
	DropIcon: class extends self.ISpriteInstance {},
	Toilet: class extends self.ISpriteInstance {},
	Cruceta: class extends self.ISpriteInstance {},
	CrucetaButton: class extends self.ISpriteInstance {},
	IntestineWall: class extends self.ITiledBackgroundInstance {},
	Particle: class extends self.ISpriteInstance {},
	BTN_Enzyme: class extends self.ISpriteInstance {},
	TXT_EnzymeButtons: class extends self.ITextInstance {},
	FlyingParticles: class extends self.ISpriteInstance {},
	Stimulis: class extends self.ISpriteInstance {},
	HandOut: class extends self.ISpriteInstance {},
	Ears: class extends self.ISpriteInstance {},
	HandTouchingArea: class extends self.ISpriteInstance {},
	EarsTouchingArea: class extends self.ISpriteInstance {},
	EyesTouchingArea: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	StimuliTimeBar: class extends self.ITiledBackgroundInstance {},
	Character: class extends self.ISpriteInstance {},
	SkinFloor: class extends self.ISpriteInstance {},
	SunBlock: class extends self.ISpriteInstance {},
	Jacket: class extends self.ISpriteInstance {},
	MovingPlatform: class extends self.ISpriteInstance {},
	Sun: class extends self.ISpriteInstance {},
	Pool: class extends self.ISpriteInstance {},
	DisapearingPlatform: class extends self.ISpriteInstance {},
	BodyTemperatureBar: class extends self.ITiledBackgroundInstance {},
	UVDAMAGEBar: class extends self.ITiledBackgroundInstance {},
	JumoButton: class extends self.ISpriteInstance {},
	CharacterPopUp: class extends self.ISpriteInstance {},
	SpermCell: class extends self.ISpriteInstance {},
	SpermGroup: class extends self.ISpriteInstance {},
	UterusWalls: class extends self.ISpriteInstance {},
	Acid: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	UterusWallsObstacle: class extends self.ISpriteInstance {},
	Bubbles: class extends self.ISpriteInstance {},
	OvumHUD: class extends self.ISpriteInstance {},
	SpermCellHUD: class extends self.ISpriteInstance {},
	Ovum: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	CellAvatar: class extends self.ISpriteInstance {},
	DialogBox: class extends self.ISpriteInstance {},
	TXT_Dialogs: class extends self.ITextInstance {},
	ButtonForward: class extends self.ISpriteInstance {},
	Hand: class extends self.ISpriteInstance {},
	Dialog_Elements: class extends self.ISpriteInstance {},
	ArmsAndLegs: class extends self.ISpriteInstance {},
	Pipes: class extends self.ISpriteInstance {},
	TouchingAreaObjects: class extends self.ISpriteInstance {},
	SkinElements: class extends self.ISpriteInstance {}
}